!function(a)
{
  function s(a,s,n)  
  {
  var 
  t=a[Math.floor(Math.random()*a.length)],
  e=s[Math.floor(Math.random()*s.length)],
  l=n[Math.floor(Math.random()*n.length)];
  return[t,e,l]
  }
function n()
  {
  var n=a(".fucking.description .sentence");  
      e=s(o,r,p,q),
      l=e[2],
        //changing l=e[2], ----> l=e[3], doesnt seem to do anything :!
      
    a(".insult h1.ass").html(e[0]+" "+e[1]),
      //this is the <ASS>
    n.html(e[2]),
      //this outputs the sentence
      //e[0] is the stock 
      //e[1] is 
      //e[2] is sentence
      //e[3] is 
        
    n.find("span.ass").html(e[0]+" "+e[1]),
      
    n.find("span.stock").html(e[0]),
      //e[0] is the stock 
      //e[1] is strategy 
      //e[2] is the sentence 
      //e[3] is undefined 
    // need to go to the main repository and add the custom CSS tag on the .CSS page.
      
    n.find("span.aan").html(t(e[0])) 
      //(l(e[0])) is ________
      //(l(e[0])) is ________
      //(l(e[0])) is ________
      //(l(e[0])) is ________
  
  }
  
    function t(a)
      {
        return"a"===a.toLowerCase().charAt(0)?"an":"a"
        
      }
    var e="",l="",
    o=[
"$MMM",
"$AOS",
"$ABT",
"$ABBV",
"$ACN",
"$ATVI",
"$AYI",
"$ADBE",
"$AAP",
"$AMD",
"$AES",
"$AET",
"$AMG",
"$AFL",
"$A",
"$APD",
"$AKAM",
"$ALK",
"$ALB",
"$ARE",
"$ALXN",
"$ALGN",
"$ALLE",
"$AGN",
"$ADS",
"$LNT",
"$ALL",
"$GOOGL",
"$GOOG",
"$MO",
"$AMZN",
"$AEE",
"$AAL",
"$AEP",
"$AXP",
"$AIG",
"$AMT",
"$AWK",
"$AMP",
"$ABC",
"$AME",
"$AMGN",
"$APH",
"$APC",
"$ADI",
"$ANDV",
"$ANSS",
"$ANTM",
"$AON",
"$APA",
"$AIV",
"$AAPL",
"$AMAT",
"$APTV",
"$ADM",
"$ARNC",
"$AJG",
"$AIZ",
"$T",
"$ADSK",
"$ADP",
"$AZO",
"$AVB",
"$AVY",
"$BHGE",
"$BLL",
"$BAC",
"$BAX",
"$BBT",
"$BDX",
"$BRK.B",
"$BBY",
"$BIIB",
"$BLK",
"$HRB",
"$BA",
"$BWA",
"$BXP",
"$BSX",
"$BHF",
"$BMY",
"$AVGO",
"$BF.B",
"$CHRW",
"$CA",
"$COG",
"$CDNS",
"$CPB",
"$COF",
"$CAH",
"$KMX",
"$CCL",
"$CAT",
"$CBOE",
"$CBG",
"$CBS",
"$CELG",
"$CNC",
"$CNP",
"$CTL",
"$CERN",
"$CF",
"$SCHW",
"$CHTR",
"$CHK",
"$CVX",
"$CMG",
"$CB",
"$CHD",
"$CI",
"$XEC",
"$CINF",
"$CTAS",
"$CSCO",
"$C",
"$CFG",
"$CTXS",
"$CME",
"$CMS",
"$KO",
"$CTSH",
"$CL",
"$CMCSA",
"$CMA",
"$CAG",
"$CXO",
"$COP",
"$ED",
"$STZ",
"$GLW",
"$COST",
"$COTY",
"$CCI",
"$CSRA",
"$CSX",
"$CMI",
"$CVS",
"$DHI",
"$DHR",
"$DRI",
"$DVA",
"$DE",
"$DAL",
"$XRAY",
"$DVN",
"$DLR",
"$DFS",
"$DISCA",
"$DISCK",
"$DISH",
"$DG",
"$DLTR",
"$D",
"$DOV",
"$DWDP",
"$DPS",
"$DTE",
"$DUK",
"$DRE",
"$DXC",
"$ETFC",
"$EMN",
"$ETN",
"$EBAY",
"$ECL",
"$EIX",
"$EW",
"$EA",
"$EMR",
"$ETR",
"$EVHC",
"$EOG",
"$EQT",
"$EFX",
"$EQIX",
"$EQR",
"$ESS",
"$EL",
"$RE",
"$ES",
"$EXC",
"$EXPE",
"$EXPD",
"$ESRX",
"$EXR",
"$XOM",
"$FFIV",
"$FB",
"$FAST",
"$FRT",
"$FDX",
"$FIS",
"$FITB",
"$FE",
"$FISV",
"$FLIR",
"$FLS",
"$FLR",
"$FMC",
"$FL",
"$F",
"$FTV",
"$FBHS",
"$BEN",
"$FCX",
"$GPS",
"$GRMN",
"$IT",
"$GD",
"$GE",
"$GGP",
"$GIS",
"$GM",
"$GPC",
"$GILD",
"$GPN",
"$GS",
"$GT",
"$GWW",
"$HAL",
"$HBI",
"$HOG",
"$HRS",
"$HIG",
"$HAS",
"$HCA",
"$HCP",
"$HP",
"$HSIC",
"$HES",
"$HPE",
"$HLT",
"$HOLX",
"$HD",
"$HON",
"$HRL",
"$HST",
"$HPQ",
"$HUM",
"$HBAN",
"$HII",
"$IDXX",
"$INFO",
"$ITW",
"$ILMN",
"$INCY",
"$IR",
"$INTC",
"$ICE",
"$IBM",
"$IP",
"$IPG",
"$IFF",
"$INTU",
"$ISRG",
"$IVZ",
"$IQV",
"$IRM",
"$JBHT",
"$JEC",
"$SJM",
"$JNJ",
"$JCI",
"$JPM",
"$JNPR",
"$KSU",
"$K",
"$KEY",
"$KMB",
"$KIM",
"$KMI",
"$KLAC",
"$KSS",
"$KHC",
"$KR",
"$LB",
"$LLL",
"$LH",
"$LRCX",
"$LEG",
"$LEN",
"$LUK",
"$LLY",
"$LNC",
"$LKQ",
"$LMT",
"$L",
"$LOW",
"$LYB",
"$MTB",
"$MAC",
"$M",
"$MRO",
"$MPC",
"$MAR",
"$MMC",
"$MLM",
"$MAS",
"$MA",
"$MAT",
"$MKC",
"$MCD",
"$MCK",
"$MDT",
"$MRK",
"$MET",
"$MTD",
"$MGM",
"$KORS",
"$MCHP",
"$MU",
"$MSFT",
"$MAA",
"$MHK",
"$TAP",
"$MDLZ",
"$MON",
"$MNST",
"$MCO",
"$MS",
"$MSI",
"$MYL",
"$NDAQ",
"$NOV",
"$NAVI",
"$NTAP",
"$NFLX",
"$NWL",
"$NFX",
"$NEM",
"$NWSA",
"$NWS",
"$NEE",
"$NLSN",
"$NKE",
"$NI",
"$NBL",
"$JWN",
"$NSC",
"$NTRS",
"$NOC",
"$NCLH",
"$NRG",
"$NUE",
"$NVDA",
"$ORLY",
"$OXY",
"$OMC",
"$OKE",
"$ORCL",
"$PCAR",
"$PKG",
"$PH",
"$PDCO",
"$PAYX",
"$PYPL",
"$PNR",
"$PBCT",
"$PEP",
"$PKI",
"$PRGO",
"$PFE",
"$PCG",
"$PM",
"$PSX",
"$PNW",
"$PXD",
"$PNC",
"$RL",
"$PPG",
"$PPL",
"$PX",
"$PCLN",
"$PFG",
"$PG",
"$PGR",
"$PLD",
"$PRU",
"$PEG",
"$PSA",
"$PHM",
"$PVH",
"$QRVO",
"$QCOM",
"$PWR",
"$DGX",
"$RRC",
"$RJF",
"$RTN",
"$O",
"$RHT",
"$REG",
"$REGN",
"$RF",
"$RSG",
"$RMD",
"$RHI",
"$ROK",
"$COL",
"$ROP",
"$ROST",
"$RCL",
"$SPGI",
"$CRM",
"$SBAC",
"$SCG",
"$SLB",
"$SNI",
"$STX",
"$SEE",
"$SRE",
"$SHW",
"$SIG",
"$SPG",
"$SWKS",
"$SLG",
"$SNA",
"$SO",
"$LUV",
"$SWK",
"$SBUX",
"$STT",
"$SRCL",
"$SYK",
"$STI",
"$SYMC",
"$SYF",
"$SNPS",
"$SYY",
"$TROW",
"$TPR",
"$TGT",
"$TEL",
"$FTI",
"$TXN",
"$TXT",
"$BK",
"$CLX",
"$COO",
"$HSY",
"$MOS",
"$TRV",
"$DIS",
"$TMO",
"$TIF",
"$TWX",
"$TJX",
"$TMK",
"$TSS",
"$TSCO",
"$TDG",
"$TRIP",
"$FOXA",
"$FOX",
"$TSN",
"$USB",
"$UDR",
"$ULTA",
"$UAA",
"$UA",
"$UNP",
"$UAL",
"$UNH",
"$UPS",
"$URI",
"$UTX",
"$UHS",
"$UNM",
"$VFC",
"$VLO",
"$VAR",
"$VTR",
"$VRSN",
"$VRSK",
"$VZ",
"$VRTX",
"$VIAB",
"$V",
"$VNO",
"$VMC",
"$WMT",
"$WBA",
"$WM",
"$WAT",
"$WEC",
"$WFC",
"$HCN",
"$WDC",
"$WU",
"$WRK",
"$WY",
"$WHR",
"$WMB",
"$WLTW",
"$WYN",
"$WYNN",
"$XEL",
"$XRX",
"$XLNX",
"$XL",
"$XYL",
"$YUM",
"$ZBH",
"$ZION",
"$ZTS"
],
   
 q=[
      "works",
      "probably",
    ],
        
 r=[
    "call",
    "naked put",
    "long straddle",
    "calendar spread",
    ],
              
    p=[
" That <span class='ass'></span> is <span class='aan'></span> major bubble shitstain ",
" That <span class='ass'></span> is <span class='aan'></span> big spastic wanker ",
" That <span class='ass'></span> is <span class='aan'></span> big camel cheesedick ",
" That <span class='ass'></span> is <span class='aan'></span> large pusher farmer ",
" That <span class='ass'></span> is <span class='aan'></span> major canoe douchenozzle ",
" That <span class='ass'></span> is <span class='aan'></span> huge nugget asshat ",
" That <span class='ass'></span> is <span class='aan'></span> big muncher Buttmunch ",
" That <span class='ass'></span> is <span class='aan'></span> huge blister sandwich ",
" That <span class='ass'></span> is <span class='aan'></span> enormous spastic cranker ",
" That <span class='ass'></span> is <span class='aan'></span> big bubble mouth-breather ",
" That <span class='ass'></span> is <span class='aan'></span> huge biscuit dickbreath ",
" That <span class='ass'></span> is <span class='aan'></span> major taco taco ",
" That <span class='ass'></span> is <span class='aan'></span> big sucker fire ",
" That <span class='ass'></span> is <span class='aan'></span> big nozzle nugget ",
" That <span class='ass'></span> is <span class='aan'></span> large cracker tard ",
" That <span class='ass'></span> is <span class='aan'></span> large nozzle cuntmuscle ",
" That <span class='ass'></span> is <span class='aan'></span> huge butt fister ",
" That <span class='ass'></span> is <span class='aan'></span> enormous farmer shitshaker ",
" That <span class='ass'></span> is <span class='aan'></span> major cock-juggling fire ",
" That <span class='ass'></span> is <span class='aan'></span> major wanker cuntkicker ",
" That <span class='ass'></span> is <span class='aan'></span> huge canoe rumpleforeskin ",
" That <span class='ass'></span> is <span class='aan'></span> enormous fister tard ",
" That <span class='ass'></span> is <span class='aan'></span> large cracker cockmuppet ",
" That <span class='ass'></span> is <span class='aan'></span> huge canoe pigfucker ",
" That <span class='ass'></span> is <span class='aan'></span> enormous scratcher pusher ",
" That <span class='ass'></span> is <span class='aan'></span> enormous cumwad twiddler ",
" That <span class='ass'></span> is <span class='aan'></span> big hatchet jizztissue ",
" That <span class='ass'></span> is <span class='aan'></span> huge seamen cockgobbler ",
" That <span class='ass'></span> is <span class='aan'></span> large inbreeder twat ",
" That <span class='ass'></span> is <span class='aan'></span> enormous waffle cockgobbler ",
" That <span class='ass'></span> is <span class='aan'></span> enormous cranker guzzler ",
" That <span class='ass'></span> is <span class='aan'></span> major meat scratcher ",
" That <span class='ass'></span> is <span class='aan'></span> major seamen scrubber ",
" That <span class='ass'></span> is <span class='aan'></span> big sandwish Buttmunch ",
" That <span class='ass'></span> is <span class='aan'></span> major nozzle cuntmuscle ",
" That <span class='ass'></span> is <span class='aan'></span> major cracker scrubber ",
" That <span class='ass'></span> is <span class='aan'></span> enormous dumpster shitbag ",
" That <span class='ass'></span> is <span class='aan'></span> enormous muncher bag ",
" That <span class='ass'></span> is <span class='aan'></span> big cumwad nozzle ",
" That <span class='ass'></span> is <span class='aan'></span> enormous ballsack mouth-breather ",
" That <span class='ass'></span> is <span class='aan'></span> big nugget pigfucker ",
" That <span class='ass'></span> is <span class='aan'></span> enormous cock-juggling cracker ",
" That <span class='ass'></span> is <span class='aan'></span> enormous bucket guzzler ",
" That <span class='ass'></span> is <span class='aan'></span> enormous monkey tard ",
" That <span class='ass'></span> is <span class='aan'></span> major fuckrag asshat ",
" That <span class='ass'></span> is <span class='aan'></span> enormous fat pusher ",
" That <span class='ass'></span> is <span class='aan'></span> huge blister fuckface ",
" That <span class='ass'></span> is <span class='aan'></span> big monkey wanker ",
" That <span class='ass'></span> is <span class='aan'></span> big inbreeder Buttmunch ",
" That <span class='ass'></span> is <span class='aan'></span> major pistol douchenozzle ",
      //"That <span class='ass'></span> is really a major <span class='aan'></span> <span class='stock'></span>"
       // "That <span class='ass'></span> just cut me off!",
       //"My boss is a major <span class='ass'></span>!",
       // "Don't tell her I said this, but that dude she's with is a real <span class='ass'></span>!",
       // "Quit being such <span class='aan'></span> <span class='ass'></span>!",
       // "The only people who would vote for that guy are total <span class='ass'></span>s!",
       // "What are you, some kind of <span class='ass'></span>?",
       // "Dude's a real <span class='ass'></span>, you know what I mean?",
       // "He's got an ego like <span class='aan'></span> is a total <span class='ass'></span>!",
       // "She was being a real <span class='ass'></span> at the store today!",
       // "That <span class='ass'></span> developer's code refuses to compile!",
       // "Her kids are total <span class='ass'></span>s!",
       //  "Whoever wrote this API documentation is a complete <span class='ass'></span>!",
       // "That guy has the personality of <span class='aan'></span> <span class='ass'></span>!",
       //  "I'm pretty sure I was a total <span class='ass'></span> at the bar last night.",
       // "What kind of <span class='ass'></span> buys pre-ground coffee?",
       //  "I'd rather get <span class='aan'></span> <span class='ass'></span> to the eye than sit through this lecture.",
       //  "Wow, that <span class='ass'></span> just went off the deep end.",
       // "I may be a jerk, but at least I'm not like that <span class='ass'></span> over there.",
       // "I need that like I need </span> is a total <span class='ass'></span> on my elbow.",
       // "What kind of <span class='ass'></span> slows down to merge on the highway?",
       // "You've got a face like <span class='aan'></span> is a total <span class='ass'></span>.",
       // "Nothing personal, but you're a real <span class='ass'></span>.",
       // "What a bunch of <span class='ass'></span>s.","That <span class='ass'></span> is legally dead in 27 states - plus Guam."
 
    ];
  
  
//<----Social Media Sharing---->
  
a("button.damn").on("click",n),
  n(),
  a("a.twitter-share-button").on("click",function(s){var n=a(this).attr("href"),
    o=n.split("text="),
    r=l.replace("<span class='ass'></span>",
                e[0]+" "+e[1]);
    r=r.replace("<span class='aan'></span>",
                t(e[0]));
    q=l.replace("<span class='stock'></span>",
             e[0]);
    // q must be updated to match e[0] as above---->currently broken
var p=o[0]+"text="+e[0]+" "+e[1]+' (noun) "'+r+'" Get yours at';
   a(this).attr("href",encodeURI(p))})}(jQuery);
