!function(a)
{
  function s(a,s,n)  
  {
  var t=a[Math.floor(Math.random()*a.length)],
  e=s[Math.floor(Math.random()*s.length)],
  l=n[Math.floor(Math.random()*n.length)];
  return[t,e,l]
  }
function n()
  {
  var n=a(".fucking.description .sentence");
    e=s(o,r,p),l=e[2],
    a(".insult h1.ass").html(e[0]+" "+e[1]),
    n.html(e[2]),
    n.find("span.ass").html(e[0]+" "+e[1]),
    n.find("span.aan").html(t(e[0]))
    
  }
    function t(a)
      {
        return"a"===a.toLowerCase().charAt(0)?"an":"a"
        
      }
    var e="",l="",
    o=[
"$MMM",
"$AOS",
"$ABT",
"$ABBV",
"$ACN",
"$ATVI",
"$AYI",
"$ADBE",
"$AAP",
"$AMD",
"$AES",
"$AET",
"$AMG",
"$AFL",
"$A",
"$APD",
"$AKAM",
"$ALK",
"$ALB",
"$ARE",
"$ALXN",
"$ALGN",
"$ALLE",
"$AGN",
"$ADS",
"$LNT",
"$ALL",
"$GOOGL",
"$GOOG",
"$MO",
"$AMZN",
"$AEE",
"$AAL",
"$AEP",
"$AXP",
"$AIG",
"$AMT",
"$AWK",
"$AMP",
"$ABC",
"$AME",
"$AMGN",
"$APH",
"$APC",
"$ADI",
"$ANDV",
"$ANSS",
"$ANTM",
"$AON",
"$APA",
"$AIV",
"$AAPL",
"$AMAT",
"$APTV",
"$ADM",
"$ARNC",
"$AJG",
"$AIZ",
"$T",
"$ADSK",
"$ADP",
"$AZO",
"$AVB",
"$AVY",
"$BHGE",
"$BLL",
"$BAC",
"$BAX",
"$BBT",
"$BDX",
"$BRK.B",
"$BBY",
"$BIIB",
"$BLK",
"$HRB",
"$BA",
"$BWA",
"$BXP",
"$BSX",
"$BHF",
"$BMY",
"$AVGO",
"$BF.B",
"$CHRW",
"$CA",
"$COG",
"$CDNS",
"$CPB",
"$COF",
"$CAH",
"$KMX",
"$CCL",
"$CAT",
"$CBOE",
"$CBG",
"$CBS",
"$CELG",
"$CNC",
"$CNP",
"$CTL",
"$CERN",
"$CF",
"$SCHW",
"$CHTR",
"$CHK",
"$CVX",
"$CMG",
"$CB",
"$CHD",
"$CI",
"$XEC",
"$CINF",
"$CTAS",
"$CSCO",
"$C",
"$CFG",
"$CTXS",
"$CME",
"$CMS",
"$KO",
"$CTSH",
"$CL",
"$CMCSA",
"$CMA",
"$CAG",
"$CXO",
"$COP",
"$ED",
"$STZ",
"$GLW",
"$COST",
"$COTY",
"$CCI",
"$CSRA",
"$CSX",
"$CMI",
"$CVS",
"$DHI",
"$DHR",
"$DRI",
"$DVA",
"$DE",
"$DAL",
"$XRAY",
"$DVN",
"$DLR",
"$DFS",
"$DISCA",
"$DISCK",
"$DISH",
"$DG",
"$DLTR",
"$D",
"$DOV",
"$DWDP",
"$DPS",
"$DTE",
"$DUK",
"$DRE",
"$DXC",
"$ETFC",
"$EMN",
"$ETN",
"$EBAY",
"$ECL",
"$EIX",
"$EW",
"$EA",
"$EMR",
"$ETR",
"$EVHC",
"$EOG",
"$EQT",
"$EFX",
"$EQIX",
"$EQR",
"$ESS",
"$EL",
"$RE",
"$ES",
"$EXC",
"$EXPE",
"$EXPD",
"$ESRX",
"$EXR",
"$XOM",
"$FFIV",
"$FB",
"$FAST",
"$FRT",
"$FDX",
"$FIS",
"$FITB",
"$FE",
"$FISV",
"$FLIR",
"$FLS",
"$FLR",
"$FMC",
"$FL",
"$F",
"$FTV",
"$FBHS",
"$BEN",
"$FCX",
"$GPS",
"$GRMN",
"$IT",
"$GD",
"$GE",
"$GGP",
"$GIS",
"$GM",
"$GPC",
"$GILD",
"$GPN",
"$GS",
"$GT",
"$GWW",
"$HAL",
"$HBI",
"$HOG",
"$HRS",
"$HIG",
"$HAS",
"$HCA",
"$HCP",
"$HP",
"$HSIC",
"$HES",
"$HPE",
"$HLT",
"$HOLX",
"$HD",
"$HON",
"$HRL",
"$HST",
"$HPQ",
"$HUM",
"$HBAN",
"$HII",
"$IDXX",
"$INFO",
"$ITW",
"$ILMN",
"$INCY",
"$IR",
"$INTC",
"$ICE",
"$IBM",
"$IP",
"$IPG",
"$IFF",
"$INTU",
"$ISRG",
"$IVZ",
"$IQV",
"$IRM",
"$JBHT",
"$JEC",
"$SJM",
"$JNJ",
"$JCI",
"$JPM",
"$JNPR",
"$KSU",
"$K",
"$KEY",
"$KMB",
"$KIM",
"$KMI",
"$KLAC",
"$KSS",
"$KHC",
"$KR",
"$LB",
"$LLL",
"$LH",
"$LRCX",
"$LEG",
"$LEN",
"$LUK",
"$LLY",
"$LNC",
"$LKQ",
"$LMT",
"$L",
"$LOW",
"$LYB",
"$MTB",
"$MAC",
"$M",
"$MRO",
"$MPC",
"$MAR",
"$MMC",
"$MLM",
"$MAS",
"$MA",
"$MAT",
"$MKC",
"$MCD",
"$MCK",
"$MDT",
"$MRK",
"$MET",
"$MTD",
"$MGM",
"$KORS",
"$MCHP",
"$MU",
"$MSFT",
"$MAA",
"$MHK",
"$TAP",
"$MDLZ",
"$MON",
"$MNST",
"$MCO",
"$MS",
"$MSI",
"$MYL",
"$NDAQ",
"$NOV",
"$NAVI",
"$NTAP",
"$NFLX",
"$NWL",
"$NFX",
"$NEM",
"$NWSA",
"$NWS",
"$NEE",
"$NLSN",
"$NKE",
"$NI",
"$NBL",
"$JWN",
"$NSC",
"$NTRS",
"$NOC",
"$NCLH",
"$NRG",
"$NUE",
"$NVDA",
"$ORLY",
"$OXY",
"$OMC",
"$OKE",
"$ORCL",
"$PCAR",
"$PKG",
"$PH",
"$PDCO",
"$PAYX",
"$PYPL",
"$PNR",
"$PBCT",
"$PEP",
"$PKI",
"$PRGO",
"$PFE",
"$PCG",
"$PM",
"$PSX",
"$PNW",
"$PXD",
"$PNC",
"$RL",
"$PPG",
"$PPL",
"$PX",
"$PCLN",
"$PFG",
"$PG",
"$PGR",
"$PLD",
"$PRU",
"$PEG",
"$PSA",
"$PHM",
"$PVH",
"$QRVO",
"$QCOM",
"$PWR",
"$DGX",
"$RRC",
"$RJF",
"$RTN",
"$O",
"$RHT",
"$REG",
"$REGN",
"$RF",
"$RSG",
"$RMD",
"$RHI",
"$ROK",
"$COL",
"$ROP",
"$ROST",
"$RCL",
"$SPGI",
"$CRM",
"$SBAC",
"$SCG",
"$SLB",
"$SNI",
"$STX",
"$SEE",
"$SRE",
"$SHW",
"$SIG",
"$SPG",
"$SWKS",
"$SLG",
"$SNA",
"$SO",
"$LUV",
"$SWK",
"$SBUX",
"$STT",
"$SRCL",
"$SYK",
"$STI",
"$SYMC",
"$SYF",
"$SNPS",
"$SYY",
"$TROW",
"$TPR",
"$TGT",
"$TEL",
"$FTI",
"$TXN",
"$TXT",
"$BK",
"$CLX",
"$COO",
"$HSY",
"$MOS",
"$TRV",
"$DIS",
"$TMO",
"$TIF",
"$TWX",
"$TJX",
"$TMK",
"$TSS",
"$TSCO",
"$TDG",
"$TRIP",
"$FOXA",
"$FOX",
"$TSN",
"$USB",
"$UDR",
"$ULTA",
"$UAA",
"$UA",
"$UNP",
"$UAL",
"$UNH",
"$UPS",
"$URI",
"$UTX",
"$UHS",
"$UNM",
"$VFC",
"$VLO",
"$VAR",
"$VTR",
"$VRSN",
"$VRSK",
"$VZ",
"$VRTX",
"$VIAB",
"$V",
"$VNO",
"$VMC",
"$WMT",
"$WBA",
"$WM",
"$WAT",
"$WEC",
"$WFC",
"$HCN",
"$WDC",
"$WU",
"$WRK",
"$WY",
"$WHR",
"$WMB",
"$WLTW",
"$WYN",
"$WYNN",
"$XEL",
"$XRX",
"$XLNX",
"$XL",
"$XYL",
"$YUM",
"$ZBH",
"$ZION",
"$ZTS"
],
 r=[
    'Albatross Spread',
    'Bear Butterfly Spread',
    'Bear Call Spread',
    ],

    p=[
        "That <span class='aan'></span> is a real <span class='ass'></span>!",
       // "That <span class='ass'></span> just cut me off!",
       //"My boss is a major <span class='ass'></span>!",
       // "Don't tell her I said this, but that dude she's with is a real <span class='ass'></span>!",
       // "Quit being such <span class='aan'></span> <span class='ass'></span>!",
       // "The only people who would vote for that guy are total <span class='ass'></span>s!",
       // "What are you, some kind of <span class='ass'></span>?",
       // "Dude's a real <span class='ass'></span>, you know what I mean?",
       //"He's got an ego like <span class='aan'></span> <span class='ass'></span>!",
       // "She was being a real <span class='ass'></span> at the store today!",
       // "That <span class='ass'></span> developer's code refuses to compile!",
       // "Her kids are total <span class='ass'></span>s!",
       //  "Whoever wrote this API documentation is a complete <span class='ass'></span>!",
       // "That guy has the personality of <span class='aan'></span> <span class='ass'></span>!",
       //  "I'm pretty sure I was a total <span class='ass'></span> at the bar last night.",
       // "What kind of <span class='ass'></span> buys pre-ground coffee?",
       //  "I'd rather get <span class='aan'></span> <span class='ass'></span> to the eye than sit through this lecture.",
       //  "Wow, that <span class='ass'></span> just went off the deep end.",
       // "I may be a jerk, but at least I'm not like that <span class='ass'></span> over there.",
       // "I need that like I need <span class='aan'></span> is a total <span class='ass'></span> on my elbow.",
       // "What kind of <span class='ass'></span> slows down to merge on the highway?",
       //  "You've got a face like <span class='aan'></span> is a total <span class='ass'></span>.",
       // "Nothing personal, but you're a real <span class='ass'></span>.",
       // "What a bunch of <span class='ass'></span>s.","That <span class='ass'></span> is legally dead in 27 states - plus Guam."
    ];
];

	function randomUpSomeShit( cussing, fuckAssNoun, fuckingDescriptions ) {
		// Randomizing shit bitches and returning the shit
		var randCussing = cussing[ Math.floor( Math.random()*cussing.length ) ];
		var randFuckAssNoun = fuckAssNoun[ Math.floor(Math.random()*fuckAssNoun.length ) ];
		var randFuckingDescription = fuckingDescriptions[ Math.floor( Math.random()*fuckingDescriptions.length ) ];

		return [ randCussing, randFuckAssNoun, randFuckingDescription ];
	}

	function randThatShitUp() {
		var $fuckingTarget = $( '.fucking.description .sentence' );
		randFuckingArray = randomUpSomeShit( cussing, fuckAssNoun, fuckingDescriptions );
		fuckingDescription = randFuckingArray[2];

		// Swapping out the title bitches
		$( '.insult h1.ass' ).html( randFuckingArray[0] + ' ' + randFuckingArray[1] );

		// Swapping out the descriptions bitches
		$fuckingTarget.html( randFuckingArray[2] );
		$fuckingTarget.find( 'span.ass' ).html( randFuckingArray[0] + ' ' + randFuckingArray[1] );

		// Fucking a or an
		$fuckingTarget.find( 'span.aan' ).html( fuckingAorAn( randFuckingArray[0] ) );
	}

	function fuckingAorAn( shitWord ) {
		// Fucking simple right now since there's only one 'A' word.
		return 'a' === shitWord.toLowerCase().charAt(0) ? 'an' : 'a';
	}

	// On click bitches
	$( 'button.damn' ).on( 'click', randThatShitUp );

	// On load bitches
	randThatShitUp();

	$( 'a.twitter-share-button' ).on( 'click', function( e ) {

		var fuckingUrl = $( this ).attr( 'href' );
		var fuckingSpit = fuckingUrl.split( 'text=' );
		var fuckingDescriptionAgain = fuckingDescription.replace( '<span class=\'ass\'></span>', randFuckingArray[0] + ' ' + randFuckingArray[1] );
		fuckingDescriptionAgain = fuckingDescriptionAgain.replace( '<span class=\'aan\'></span>', fuckingAorAn( randFuckingArray[0] ) );
		var newFuckingUrl = fuckingSpit[0] + 'text=' + randFuckingArray[0] + ' ' + randFuckingArray[1] + ' (noun) "' + fuckingDescriptionAgain + '" Get yours at' ;

		$( this ).attr( 'href', encodeURI( newFuckingUrl ) );

	} );


} )( jQuery );
